[build-system]
requires = ["setuptools>=66.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version={attr="kalorda.package.version"}

[project]
dynamic = ["version"]
name = "kalorda"
description = "integrated fine-tuning platform for lightweight vlmOCR models"
authors = [{ name = "kalorda", email = "postmaster@vlmocr.com" },]
keywords = [
    "vlm ocr model",
    "vlm ocr model label",
    "vlm ocr model fine-tune",
    "vlm ocr model test",
    "vllm", "ms-swift",
]
license = "Apache-2.0"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    # "deepspeed==0.16.9",
    "types-cachetools",
    "bcrypt==4.0.1",
    "passlib",
    "python-jose",
    "natsort",
    "peewee",
    "verovio",
    "pdf2image",
    "pypdfium2",
    "Spire.Pdf.Free",
    "poppler-utils",
    "pysqlite3-binary",
    "pymysql",
    "pyzmq",
    "sse-starlette",
    "qwen_vl_utils",
    "easydict",
    # deepseek_ocr sft must requires<=0.17.1 ms-swift依赖项
    "peft==0.17.1", 
    "torch==2.9.0",
    "vllm",
    "ms-swift",
    # 国际化翻译
    "babel"
]

[project.scripts]
kalorda = "kalorda.main:main"

[project.urls]
"Homepage" = "https://kalorda.vlmocr.com"
"Repository" = "https://github.com/vlmOCR/Kalorda.git"
"Bug Tracker" = "https://github.com/vlmOCR/Kalorda/issues"

[project.optional-dependencies]
dev = [
    "pre-commit>=3.6.0",
    "black>=24.8.0",
    "isort>=5.13.2",
    "flake8>=7.1.0",
    "mypy>=1.8.0",
    "flake8-docstrings>=1.7.0",
    "pydocstyle>=6.3.0"
]

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(\.
    |build
    |dist
    |venv
    |__pycache__
)/
'''


[tool.flake8]
max-line-length = 120
exclude = [".git", "__pycache__", "build", "dist", "venv", "finetune_works", "vllm_infer"]
ignore = ["C", "D", "E203", "F401", "W503"]
max-complexity = 10
docstring-convention = "google"


[tool.isort]
profile = "black"
line_length = 120
skip = ["build", "dist", "venv", "__pycache__", "finetune_works"]


[tool.mypy]
ignore_missing_imports = true
follow_imports = "skip"
strict_optional = false
warn_return_any = false
disable_error_code = ["attr-defined", "has-type", "arg-type", "return-value", "misc", "assignment"]
exclude = ["build", "dist", "venv", "__pycache__", "vllm_infer", "finetune_works"]


[tool.pydocstyle]
extend_exclude = ["build", "dist", "venv", "__pycache__"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"]





